# Generated by Django 3.2 on 2021-05-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default=False, max_length=10)),
                ('cost', models.FloatField(default=False)),
                ('shares', models.FloatField(default=False)),
            ],
        ),
    ]
